/**
 * This file is generated by Better Auth CLI.
 * Run `pnpm --filter @FastTechStack/backend auth:generate` after adjusting auth options.
 */
const BetterAuthSchema = {
  user: {
    fields: {
      name: "string",
      email: "string",
      emailVerified: "boolean",
      image: "string?",
      createdAt: "date",
      updatedAt: "date"
    }
  },
  session: {
    fields: {
      expiresAt: "date",
      token: "string",
      createdAt: "date",
      updatedAt: "date",
      ipAddress: "string?",
      userAgent: "string?",
      userId: "string"
    }
  },
  account: {
    fields: {
      accountId: "string",
      providerId: "string",
      userId: "string",
      accessToken: "string?",
      refreshToken: "string?",
      idToken: "string?",
      accessTokenExpiresAt: "date?",
      refreshTokenExpiresAt: "date?",
      scope: "string?",
      password: "string?",
      createdAt: "date",
      updatedAt: "date"
    }
  },
  verification: {
    fields: {
      identifier: "string",
      value: "string",
      expiresAt: "date",
      createdAt: "date",
      updatedAt: "date"
    }
  }
} as const;

export default BetterAuthSchema;
